### ISSUE TITLE
example raises Exception

### ISSUE THREAD

**Issue by horida** [h2non/pook#27]
```
$ python test_it.py 
Traceback (most recent call last):
  File "test_it.py", line 17, in <module>
    test_my_api()
  File "/home/repo/venv/local/lib/python2.7/site-packages/pook/api.py", line 77, in wrapper
    raise err
pook.exceptions.PookNoMatches: ('Cannot match any mock for request:', Request(
  method=GET,
  headers=HTTPHeaderDict({'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.11.1'}),
  body=None,
  url=ParseResult(scheme='http', netloc='twitter.com:80', path='/api/1/foobar', params='', query='', fragment=''),
  query={},
))
```

**Comment by h2non** [comment]
I'm sorry for that. README.rst examples are not automatically tested. You should check `examples/` directory.

**Comment by h2non** [comment]
Fixed. 

As I said, I'm working on a new release that introduces a bunch of enhancements and fixes + better documentation and more examples.
