### ISSUE TITLE
Installation fail when your system encoding is cp1251.py

### ISSUE THREAD

**Issue by sky-code** [h2non/pook#31]
I was trying to install pook on my machine with system preference encoding win-1251  and I have received exception

```
pip install --upgrade pook
Collecting pook
  Using cached pook-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sky\AppData\Local\Temp\pip-build-nd_a6pc3\pook\setup.py", line 55, in <module>
        readme = f.read()
      File "C:\Python\Python35-32\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1842: character maps to <undefined>
```
Problem in reading file `README.rst` in symbol `✘`
Explicit set encoding when calling read function in setup.py to solve this

**Comment by h2non** [comment]
This should be fixed in pook@0.1.4, which is now available at PyPI registry.

Thanks for the PR!
